#!/usr/bin/perl

use strict;
use warnings;
use File::Find;

my $resources = "resources";

my @collection;

sub collect {
    unless ($_ =~ ".+\.qrc\$" || -d $_) {
        push @collection, $File::Find::name;
    }
}

chdir $resources;
find (\&collect, ".");

my $script = $0;
$script =~ s/^[.\/\\]+//;
my $output = "<!--THIS FILE IS GENERATED BY $script - DO NOT EDIT IT BY HAND-->\n";
$output = $output . "<!DOCTYPE RCC>\n<RCC version=\"1.0\">\n<qresource>";
for my $resource (@collection) {
    $output = $output . "\n    <file>$resource</file>";
}
$output = $output . "\n</qresource>\n</RCC>\n";

open (my $fh, ">", "$resources.qrc") or die "cannot open file $resources.qrc for writing: $!";
print $fh $output;
close $fh;

exit 0;
