### THIS FILE IS GENERATED BY pri.pl - DO NOT EDIT IT BY HAND

HEADERS += \
        src/gamelistmodel.h \
        src/gamewindow.h \
        src/maincentralwidget.h \
        src/mainwindow.h \
        src/modlist.h \
        src/modtree.h

SOURCES += \
        src/gamelistmodel.cpp \
        src/gamewindow.cpp \
        src/main.cpp \
        src/maincentralwidget.cpp \
        src/mainwindow.cpp \
        src/modlist.cpp \
        src/modtree.cpp
